# Numpy

NumPy is the fundamental package for scientific computing in Python. 
Numpy is perfect for fast n-dimensional calculations. 

- Numpy Arrays (ndarray - Numpy array class) have a fixed size at creation
- Same Data type in one array and operations
- behind the scenes optimized, pre-compiled C code.
- Absence of Loops (vectorized)
- element-by-element behavior (broadcasting)

Further Information - See Help Numpy reference

In [3]:
import numpy as np

Lets start with creating an Array:
$$
   a= \begin{pmatrix}
    1 & 2 & 3 \\
    1 & 2 & 3 \\
    1 & 2 & 3 \\
    \end{pmatrix}
$$

In [4]:
a=np.array([(1,2,3), (1,2,3), (1,2,3)])

In [5]:
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [6]:
a.size

9

## Basic Operations

Elementwise behaviour:
$$
   b= \begin{pmatrix}
    1 & 2 & 3 \\
    1 & 2 & 3 \\
    1 & 2 & 3 \\
    \end{pmatrix} 
    \cdot 2
$$

In [7]:
#Multiplication Elementwise
b=a*2

In [8]:
b

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

What happens when multiplying two matrizes?

$$
   c=a\cdot b= \begin{pmatrix}
    2 & 4 & 6 \\
    2 & 4 & 6 \\
    2 & 4 & 6 \\
    \end{pmatrix} 
    \cdot 
    \begin{pmatrix}
    2 & 4 & 6 \\
    2 & 4 & 6 \\
    2 & 4 & 6 \\
    \end{pmatrix} 
$$

In [9]:
a=b
a*b

array([[ 4, 16, 36],
       [ 4, 16, 36],
       [ 4, 16, 36]])

Normally Operations are done Elementwise. 
But what about matrix product?

$$
   a\cdot b= \begin{pmatrix}
    2 & 4 & 6 \\
    2 & 4 & 6 \\
    2 & 4 & 6 \\
    \end{pmatrix} 
    \cdot 
    \begin{pmatrix}
    2 & 4 & 6 \\
    2 & 4 & 6 \\
    2 & 4 & 6 \\
    \end{pmatrix} 
    =
    \begin{pmatrix}
    24 & 48 & 72 \\
    24 & 48 & 72 \\
    24 & 48 & 72 \\
    \end{pmatrix} 
$$

In [10]:
a@b

array([[24, 48, 72],
       [24, 48, 72],
       [24, 48, 72]])

Many other Operations are implemented as functions:
Sum, Find minimium/maximum Value...


In [11]:
a.sum()

36

In [12]:
a.min()

2

In [13]:
a.max()

6

## Access Values from Arrays

a[Row,Column]

Array counting starts with 0

With : all Values can be found



In [16]:
a[:,-2]

array([4, 4, 4])

Many more Operations can be conducted with arrays! Lets have another look at the Documentation