# Manipulate Arrays


In [15]:
import numpy as np
T_t0 = np.ones((50,50))

print(T_t0)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


Access Values:
- Use square brackets [] (Different for Matlab ())
- Arrays start at 0
- First Values defines th row and second the Column

- Syntax: T_t0[row, column]
    

In [16]:
T_t0[0,0]=2
print(T_t0)

[[2. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


Access the last rows or columns with [-1], the one before with [-2] -> Matlab [end]


In [17]:
T_t0[-1,-2] =2
print(T_t0)

[[2. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 2. 1.]]


To set the Values we need to access full rows and columns -> This can be done using [:]


In [18]:
T_t0[-1,:]=2
print(T_t0)

[[2. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [2. 2. 2. ... 2. 2. 2.]]


Watch out when copying arrays! -> You assign a pointer to the same Memory id
- Use deep copy to create a new array 
- Different behaviour than Matlab -> Matlab creates a new array

In [26]:
# Example
T_2=T_t0
T_3=T_t0.copy()
print(T_2)
print(T_3)



[[2. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 3. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [2. 2. 2. ... 2. 2. 2.]]
[[2. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 3. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [2. 2. 2. ... 2. 2. 2.]]


In [27]:
# Now we change our T_t0 array
T_t0[2,-1]=3

print(T_2) #T2 has changed
print(T_3) #T3 has not changed

[[2. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 3. ... 1. 1. 3.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [2. 2. 2. ... 2. 2. 2.]]
[[2. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 3. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [2. 2. 2. ... 2. 2. 2.]]
